### PR TITLE
Set size of overlay container to fix layout in Firefox

### LINKED ISSUE #738: Overlay containers are incorrectly sized in Firefox
In Firefox, the overlay containers are very wide (several million pixels, in our laundry setup), which makes the page unusable
Laundree shown in firefox with blobs of color filling out the full width of the page

### PR DESCRIPTION
**Pull request by kimsey0**
Fixes #738. Doesn't change the layout in Chrome.

### CODE REVIEW

**Comment by kimsey0** [comment]
@budde377: Any chance to get this merged and released on laundree.io? I know this project is pretty much abandoned, but our owners' association uses and appreciates the hosted solution, and I'd love to be able to access it from my main browser with this one-liner of a fix.

**Comment by budde377** [comment]
Hi @kimsey0, unfortunately, I'm no longer affiliated with Laundree and therefore unable to help you out. You're right in that this project is pretty much un-maintained, and I don't suspect that to change any time soon, sorry.

**Comment by kimsey0** [comment]
@budde377, thanks for the answer. I'll use a userstyle for now.

Do you know who pays for the domain and hosting and if it's likely to remain up? I can see that the company on WHOIS for the domain was disbanded a month ago. It doesn't look like there's any way to pay for usage of the hosted service either.

**Comment by budde377** [comment]
I hate to disappoint again, but I have no contact with the current owner of this project. I would suggest moving to another service, or forking this and run it on your own infrastructure.

**Pull request closed without merging**
